language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew test

after_success:
  - bash $HOME/.test.sh
  - bash <(curl -s https://codecov.io/bash) -f ./build/jacocoReports/test/jacocoTestReport.xml
