language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.gradle
  
script:
  - ./gradlew test
  - ./gradlew jacocoTestReport coveralls
