language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew test

after_success:
  - pwd
  - bash <(curl -s https://codecov.io/bash)
