language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_install:
  - openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv -in encryptedKeys.tar.enc -out encryptedKeys.tar -d
  - tar xvf encryptedKeys.tar

script:
  - ./gradlew test
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
